# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PillCounter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PillCounter

  target 'PillCounterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PillCounterUITests' do
    # Pods for testing
  end

  pod 'SQLCipher', '~> 4.5'
end
